### ISSUE TITLE
Oh My IG Has Broken?

### ISSUE THREAD

**Issue by jphunnid** [inDream/oh-my-ig#1]
From yesterday It no longers pulls IG post, just shows a blank screen. 

Thought I'll bring it up incase yall wasnt aware of it yet.

**Comment by inDream** [comment]
Is it still not working? Any error message appeared in console?
(Press Win: Ctrl + Shift + J / Mac: Cmd + Opt + J)

**Comment by hn525** [comment]
Hi, it's down again. It says:
Uncaught (in promise) TypeError: Cannot read property 'count' of undefined
    at addDates.then.dates (main.js:79)
    at <anonymous>

**Comment by inDream** [comment]
@hn525 Have you logged in before click "Start Sync"?

**Comment by hn525** [comment]
@inDream Yeah, I'm logged in IG, but nothing happens.

**Comment by hn525** [comment]
It suddenly worked again today...

**Comment by inDream** [comment]
@hn525 It's fixed in 506d345ed3914b89d9b9d2d4ff1815f87d4dab32, thanks for your report.
