### ISSUE TITLE
Feed sync issues

### ISSUE THREAD

**Issue by PixelTom** [inDream/oh-my-ig#10]
Experienced on multiple machines I have.

It seems it will sync a couple of times after a cache clear but is unreliable. Seems to have happened sometime around the 20th of December.

**Comment by inDream** [comment]
Could you provide log for my investigation:

1. Go to chrome://extensions/?id=glmlgaadcaohdmmpkkllhdkpjbeibond 
2. Click top right corner "Developer mode" button
3. Inspect views -> Click "background page"
4. Click "Console" tab in top bar
5. Copy any error (red) messages here

If no error you could try Press Ctrl+R refresh or manual load feed in the popup.

**Comment by PixelTom** [comment]
![chrome_s5XZksfFOD](https://user-images.githubusercontent.com/3375026/72204474-7d658780-34cc-11ea-8bab-b665ce0d6c93.png)

**Comment by PixelTom** [comment]
Seems to be working a lot better lately. Might have been just me?
