### ISSUE TITLE
Does Not Sync. 

### ISSUE THREAD

**Issue by Rone777** [inDream/oh-my-ig#3]
This used to be my goto for instagram but now its unusable, its been not working right for  awhile but Ive been able to use a workaround by using a older version but that no longer works as well. 

Can you fix this issue? I also wont mind if this turns into a subscription based extension if it means more attention can be afforded to it that way. I really like this extension and would hate to see it just die.

**Comment by inDream** [comment]
Sorry for late reply, it should be fixed in 33ed0a3358a41eceb8efe8c9d67681de8b6f0e74.
