### ISSUE TITLE
videos have no play button. 

### ISSUE THREAD

**Issue by Rone777** [inDream/oh-my-ig#4]
This has been an issue with the newest updates but I didnt mind since i just used a older version but when the syncing issue happened I was forced to update to the latest version and now with the latest version videos have no play button so you cant watch em on the extension page or even know if its a video or not you have to go to the actual IG posters page to find out if its truly a video or just an image. I will like to see this corrected. This was a huge factor in using this extension for me. 

I repeat again, I dont mind this extension going into some sort of subscription based project if that means you are able to afford more time to it.

**Comment by inDream** [comment]
Sorry for late reply, it should be fixed in d4ca5f6d7ea95b91ee78c5da56f9ce9c74322a9c.
