### ISSUE TITLE
instagram doesnt work anymore

### ISSUE THREAD

**Issue by lashatatu** [inDream/oh-my-ig#7]
instagram photo story grab doesn't work anymore

**Comment by inDream** [comment]
It should be fixed in 79535288754e8352a2673f8dd7ac4c5e7beb8d9d thanks for your report.

**Comment by sesilkam** [comment]
> It should be fixed in [7953528](https://github.com/inDream/oh-my-ig/commit/79535288754e8352a2673f8dd7ac4c5e7beb8d9d) thanks for your report.

**Extension stopped working. Gives an error when trying to download photos from pages, groups, photos of, photos all, photos from Messanger in Facebook. Please fix it.**

![Untitfffed](https://user-images.githubusercontent.com/58599735/70803373-963f2800-1dbc-11ea-810d-8961d74c40b3.png)

**Comment by sesilkam** [comment]
> It should be fixed in [7953528](https://github.com/inDream/oh-my-ig/commit/79535288754e8352a2673f8dd7ac4c5e7beb8d9d) thanks for your report.

**DownAlbum extension stopped working. Gives an error when trying to download photos from pages, groups, photos of, photos all, photos from Messanger in Facebook. Please fix it.**

![Untitfffed](https://user-images.githubusercontent.com/58599735/70803424-b1119c80-1dbc-11ea-8ad7-44145915080a.png)
